# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        include:
          - content_type: text/markdown
            body: file://readmei.md
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Read readmei.md
        uses: juliangruber/read-file-action@v1
        with:
          path: ./readmei.md
      - name: Echo readmei.md
        run: echo ${{ steps.package.outputs.content }}
      # Runs a single command using the runners shell
      - name: Send mail
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{secrets.USERNAME}}
          password: ${{secrets.PASSWORD}}
          subject: Github Actions job result
          # Literal body: 
#         body: Build job of ${{github.repository}} completed successfully!
          # Read file contents as body:
          body: ${{matrix.body}}
          to: tejas.chauhan112@gmail.com
          from: Tejas Chauhan # <user@example.com>
          # Optional carbon copy recipients
          # Optional content type (defaults to text/plain):
          content_type: text/html
          # Optional converting Markdown to HTML (set content_type to text/html too):
          convert_markdown: true
